name: merge_localizations
description: Allows merging multiple nested .arb files into one root .arb file
version: 1.1.5
repository: https://github.com/cedvdb/merge-localizations

environment:
  sdk: ^3.3.0

dependencies:
  yaml: ^3.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
